<a href="https://colab.research.google.com/github/rogacky11/WineQT_neural_network/blob/main/WineQT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [68]:
import pandas as pd
import numpy as np
from tensorflow import keras
import seaborn as sns
from keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder, StandardScaler
from keras import models, layers
import matplotlib.pyplot as plt


import torch
import torch.nn as nn
import torch.nn.functional as F

In [69]:
df = pd.read_csv('WineQT.csv')

In [70]:
df.head(20)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0             7.4             0.700         0.00             1.9      0.076   
1             7.8             0.880         0.00             2.6      0.098   
2             7.8             0.760         0.04             2.3      0.092   
3            11.2             0.280         0.56             1.9      0.075   
4             7.4             0.700         0.00             1.9      0.076   
5             7.4             0.660         0.00             1.8      0.075   
6             7.9             0.600         0.06             1.6      0.069   
7             7.3             0.650         0.00             1.2      0.065   
8             7.8             0.580         0.02             2.0      0.073   
9             6.7             0.580         0.08             1.8      0.097   
10            5.6             0.615         0.00             1.6      0.089   
11            7.8             0.610         0.29             1.6      0.114   
12            8.5             0.280         0.56             1.8      0.092   
13            7.9             0.320         0.51             1.8      0.341   
14            7.6             0.390         0.31             2.3      0.082   
15            7.9             0.430         0.21             1.6      0.106   
16            8.5             0.490         0.11             2.3      0.084   
17            6.9             0.400         0.14             2.4      0.085   
18            6.3             0.390         0.16             1.4      0.080   
19            7.6             0.410         0.24             1.8      0.080   

    free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                  11.0                  34.0   0.9978  3.51       0.56   
1                  25.0                  67.0   0.9968  3.20       0.68   
2                  15.0                  54.0   0.9970  3.26       0.65   
3                  17.0                  60.0   0.9980  3.16       0.58   
4                  11.0                  34.0   0.9978  3.51       0.56   
5                  13.0                  40.0   0.9978  3.51       0.56   
6                  15.0                  59.0   0.9964  3.30       0.46   
7                  15.0                  21.0   0.9946  3.39       0.47   
8                   9.0                  18.0   0.9968  3.36       0.57   
9                  15.0                  65.0   0.9959  3.28       0.54   
10                 16.0                  59.0   0.9943  3.58       0.52   
11                  9.0                  29.0   0.9974  3.26       1.56   
12                 35.0                 103.0   0.9969  3.30       0.75   
13                 17.0                  56.0   0.9969  3.04       1.08   
14                 23.0                  71.0   0.9982  3.52       0.65   
15                 10.0                  37.0   0.9966  3.17       0.91   
16                  9.0                  67.0   0.9968  3.17       0.53   
17                 21.0                  40.0   0.9968  3.43       0.63   
18                 11.0                  23.0   0.9955  3.34       0.56   
19                  4.0                  11.0   0.9962  3.28       0.59   

    alcohol  quality  Id  
0       9.4        5   0  
1       9.8        5   1  
2       9.8        5   2  
3       9.8        6   3  
4       9.4        5   4  
5       9.4        5   5  
6       9.4        5   6  
7      10.0        7   7  
8       9.5        7   8  
9       9.2        5  10  
10      9.9        5  12  
11      9.1        5  13  
12     10.5        7  16  
13      9.2        6  19  
14      9.7        5  21  
15      9.5        5  22  
16      9.4        5  23  
17      9.7        6  24  
18      9.3        5  25  
19      9.5        5  26

In [71]:
df = df.drop('Id', axis=1)

In [72]:
def map_quality(value):
    return value - 3

In [73]:
df['quality'] = df['quality'].map(map_quality)

In [74]:
X = df.drop('quality', axis = 1)
y = df['quality']
X = X.values
y = y.values

In [75]:
df['quality'].value_counts()

2    483
3    462
4    143
1     33
5     16
0      6
Name: quality, dtype: int64

In [76]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=.2, shuffle=True,  random_state=50)

In [77]:
X.shape

(1143, 11)

In [78]:
df.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
dtype: object

In [79]:
# mean = x_train.mean(axis = 0)
# x_train -=mean
# std = x_train.std(axis = 0)
# x_train /= std

# x_test -= mean
# x_test /= std

In [80]:
x_train

array([[ 8.6 ,  0.52,  0.38, ...,  3.2 ,  0.52,  9.4 ],
       [ 7.5 ,  0.51,  0.02, ...,  3.36,  0.54, 10.5 ],
       [11.2 ,  0.66,  0.24, ...,  3.06,  0.72, 11.  ],
       ...,
       [ 8.3 ,  0.61,  0.3 , ...,  3.4 ,  0.61, 10.2 ],
       [ 6.7 ,  0.62,  0.21, ...,  3.52,  0.58,  9.3 ],
       [ 7.1 ,  0.68,  0.  , ...,  3.48,  0.5 ,  9.3 ]])

In [81]:
one_hot_train_y = to_categorical(y_train)
one_hot_test_y = to_categorical(y_test)
print(one_hot_train_y[1])

[0. 0. 0. 1. 0. 0.]


In [82]:
model = models.Sequential()
model.add(layers.Dense(16, activation = 'relu', input_shape = (11,)))
model.add(layers.Dense(16, activation = 'relu'))
model.add(layers.Dense(16, activation = 'relu'))
model.add(layers.Dense(6, activation = 'sigmoid'))

In [83]:
x_val = x_train[:500]
partial_x_train = x_train[500:]

y_val = one_hot_train_y[:500]
partial_y_train = one_hot_train_y[500:]

In [84]:
model.compile(optimizer = 'Adam', loss ='binary_crossentropy', metrics = ['acc'])
history = model.fit(x_train, one_hot_train_y, epochs = 100, batch_size = 90)

Epoch 1/100
11/11 [==============================] - 2s 6ms/step - loss: 3.8804 - acc: 0.1116
Epoch 2/100
11/11 [==============================] - 0s 5ms/step - loss: 2.2250 - acc: 0.0864
Epoch 3/100
11/11 [==============================] - 0s 5ms/step - loss: 1.0953 - acc: 0.1182
Epoch 4/100
11/11 [==============================] - 0s 5ms/step - loss: 0.6220 - acc: 0.3162
Epoch 5/100
11/11 [==============================] - 0s 6ms/step - loss: 0.4883 - acc: 0.4048
Epoch 6/100
11/11 [==============================] - 0s 5ms/step - loss: 0.4263 - acc: 0.4475
Epoch 7/100
11/11 [==============================] - 0s 5ms/step - loss: 0.3832 - acc: 0.4825
Epoch 8/100
11/11 [==============================] - 0s 5ms/step - loss: 0.3568 - acc: 0.5088
Epoch 9/100
11/11 [==============================] - 0s 6ms/step - loss: 0.3417 - acc: 0.5088
Epoch 10/100
11/11 [==============================] - 0s 5ms/step - loss: 0.3317 - acc: 0.5208
Epoch 11/100
11/11 [==============================] - 0s 6m

In [85]:
y_test

array([3, 3, 2, 3, 0, 1, 2, 2, 3, 2, 3, 3, 4, 2, 3, 2, 3, 2, 1, 1, 4, 3,
       2, 3, 3, 2, 2, 3, 3, 4, 2, 3, 4, 2, 4, 4, 2, 3, 4, 2, 2, 2, 4, 3,
       2, 3, 3, 3, 2, 2, 2, 4, 3, 4, 2, 4, 2, 2, 3, 2, 3, 2, 3, 3, 3, 3,
       3, 2, 3, 2, 2, 2, 2, 4, 2, 3, 2, 3, 4, 3, 3, 4, 2, 2, 2, 2, 3, 3,
       3, 1, 3, 2, 2, 2, 3, 2, 4, 3, 2, 3, 2, 3, 2, 2, 2, 4, 3, 2, 3, 2,
       2, 2, 2, 3, 2, 3, 2, 5, 3, 2, 3, 3, 2, 2, 3, 3, 3, 2, 3, 3, 3, 2,
       3, 2, 2, 3, 2, 2, 3, 3, 4, 2, 2, 4, 4, 2, 2, 3, 3, 2, 3, 2, 3, 2,
       3, 2, 2, 1, 2, 3, 3, 4, 1, 3, 3, 2, 3, 4, 1, 2, 4, 3, 2, 2, 2, 4,
       2, 1, 2, 2, 3, 2, 3, 4, 2, 4, 2, 3, 2, 2, 2, 2, 4, 2, 2, 2, 3, 4,
       2, 2, 3, 4, 4, 3, 2, 4, 4, 1, 4, 1, 1, 4, 4, 4, 3, 2, 2, 3, 2, 2,
       3, 4, 2, 2, 3, 2, 4, 0, 3])

In [86]:
result = model.predict(x_test)

8/8 [==============================] - 0s 2ms/step


In [87]:
pred = np.argmax(result, axis = 1)
print(pred)

[3 3 2 2 3 3 2 2 3 2 3 3 3 2 2 2 3 3 3 2 2 2 2 2 3 2 3 3 2 3 3 3 3 2 3 3 3
 2 3 3 2 2 3 3 3 3 2 3 2 2 3 3 3 3 3 3 2 2 3 3 3 3 2 2 3 3 3 3 2 3 3 2 3 3
 2 2 2 3 3 3 3 3 2 2 3 2 2 3 3 3 3 2 3 2 3 3 3 3 3 3 2 3 3 3 2 3 2 3 3 3 3
 3 2 3 2 3 2 3 2 2 3 3 3 3 2 2 3 2 2 3 2 3 3 2 2 3 2 3 3 2 3 3 3 3 3 2 3 3
 3 3 3 2 3 3 3 2 3 2 2 3 3 2 3 2 2 4 2 3 3 3 3 3 2 2 3 3 3 3 3 2 3 2 3 2 2
 3 3 3 2 2 2 2 3 3 3 2 3 3 2 3 2 3 3 3 2 3 3 3 3 3 2 3 3 3 2 2 2 3 3 3 2 3
 3 2 2 3 3 2 3]


In [88]:
proc = pred[pred==y_test]
print(len(proc)/len(y_test))

0.4585152838427948
